# Collector specific configuration
hdro_url: "http://ec2-54-174-131-205.compute-1.amazonaws.com/API/hdro_api_all.json"
qc_indicators:
  - code: "137506"
    title: "Human Development Index (HDI)"
    unit: "Index"
  - code: "138806"
    title: "Inequality-adjusted HDI (IHDI)"
    unit: "Index"
  - code: "68606"
    title: "Gender Inequality Index (GII)"
    unit: "Index"
