# Collector specific configuration
base_url: "https://hdrdata.org/api/CompositeIndices/"
qc_indicators:
  - code: "GDI"
    code_col: "#index+id"
    title: "Gender Development Index (GDI)"
    unit: "Index"
  - code: "GII"
    code_col: "#index+id"
    title: "Gender Inequality Index (GII)"
    unit: "Index"
  - code: "HDI"
    code_col: "#index+id"
    title: "Human Development Index (HDI)"
    unit: "Index"
